name = 'Hugo Bibliography'
license = 'MIT'
licenselink = 'https://github.com/dh-tech/hugo-bibliography/blob/main/LICENSE'
description = 'Hugo Theme for generating a bibliography from a Zotero library'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/dh-tech/hugo-bibliography'

# If you have a running demo of the theme
#demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['bibliography']
#features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'Tatsat Jha', homepage = 'https://github.com/TatsatJha'},
  {name = 'Hugo-Bibliography contributors', homepage = 'https://github.com/dh-tech/hugo-bibliography/graphs/contributors'}
]
